# Generated by Django 3.2.4 on 2021-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard user – educational purposes only'), ('Professional', 'Professional user – for use with City of Raleigh design review (requires City approval)')], max_length=20, null=True, verbose_name='User Type'),
        ),
    ]
