# Generated by Django 3.2.9 on 2022-01-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costitemuserassumptions',
            options={'verbose_name': 'Scenario Structure Cost Item User Assumption', 'verbose_name_plural': 'Scenario Structure Cost Item User Assumptions'},
        ),
        migrations.RemoveField(
            model_name='costitemdefaultequations',
            name='r_ratio',
        ),
        migrations.RemoveField(
            model_name='costitemuserassumptions',
            name='r_ratio',
        ),
    ]
