# Generated by Django 2.1.2 on 2019-07-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arealfeatures',
            old_name='curb_and_gutter_area',
            new_name='landscape_area',
        ),
        migrations.RenameField(
            model_name='arealfeatures',
            old_name='curb_and_gutter_checkbox',
            new_name='landscape_checkbox',
        ),
    ]
