# Generated by Django 2.1.2 on 2019-07-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_auto_20190716_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionalstructures',
            name='curb_and_gutter_area',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='conventionalstructures',
            name='curb_and_gutter_checkbox',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
