# Generated by Django 2.1.2 on 2019-08-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_auto_20190716_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitemdefaultcosts',
            name='equation',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Construction Costs Equation '),
        ),
    ]
