# Generated by Django 2.1.2 on 2019-08-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_costitemdefaultcosts_equation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItemDefaultEquations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation_tx', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Equation')),
                ('a_area', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Area (a)')),
                ('z_depth', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Depth (z)')),
                ('d_density', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Density (d)')),
                ('r_ratio', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Ratio (r)')),
                ('n_number', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Count (n)')),
                ('costitem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='scenario.CostItem', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cost Item Default Equations',
            },
        ),
    ]
