# Generated by Django 2.1.2 on 2019-08-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_costitemdefaultequations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costitemdefaultequations',
            name='costitem',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='scenario.CostItem'),
        ),
    ]
