# Generated by Django 2.1.2 on 2019-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0006_auto_20190815_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitemdefaultequations',
            name='help_text',
            field=models.CharField(default='Help Text', max_length=1000),
        ),
    ]
