# Generated by Django 2.1.2 on 2019-08-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0007_costitemdefaultequations_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costitemuserassumptions',
            name='construction_cost_factor_equation',
        ),
        migrations.RemoveField(
            model_name='costitemuserassumptions',
            name='factor_assumption_tx',
        ),
        migrations.RemoveField(
            model_name='costitemuserassumptions',
            name='sizing_factor_k',
        ),
        migrations.RemoveField(
            model_name='costitemuserassumptions',
            name='sizing_factor_n',
        ),
        migrations.AddField(
            model_name='costitemuserassumptions',
            name='a_area',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Area (a)'),
        ),
        migrations.AddField(
            model_name='costitemuserassumptions',
            name='n_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Number (n)'),
        ),
    ]
