# Generated by Django 2.1.2 on 2019-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0008_auto_20190815_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costitemuserassumptions',
            name='conversion_factor',
        ),
        migrations.AddField(
            model_name='costitemuserassumptions',
            name='d_density',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Density (d)'),
        ),
        migrations.AddField(
            model_name='costitemuserassumptions',
            name='r_ratio',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Ratio (r)'),
        ),
        migrations.AddField(
            model_name='costitemuserassumptions',
            name='z_depth',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Depth (z)'),
        ),
        migrations.AlterField(
            model_name='costitemuserassumptions',
            name='n_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Count (n)'),
        ),
    ]
