# Generated by Django 2.1.2 on 2019-08-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0009_auto_20190815_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItemDefaultFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_area', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Area (a)')),
                ('z_depth', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Depth (z)')),
                ('d_density', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Density (d)')),
                ('n_number', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Count (n)')),
                ('costitem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='scenario.CostItem')),
                ('structure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='scenario.Structures')),
            ],
            options={
                'verbose_name_plural': 'Structure Cost Item Default Factors',
            },
        ),
        migrations.AlterUniqueTogether(
            name='costitemdefaultassumptions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='costitemdefaultassumptions',
            name='costitem',
        ),
        migrations.RemoveField(
            model_name='costitemdefaultassumptions',
            name='structure',
        ),
        migrations.DeleteModel(
            name='CostItemDefaultAssumptions',
        ),
        migrations.AlterUniqueTogether(
            name='costitemdefaultfactors',
            unique_together={('structure', 'costitem')},
        ),
    ]
